server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: resource
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /webapp/WEB-INF/views/
      suffix: .jsp
student:
  name: "wwwwww"
  age: 22